package Vue;

import Controle.modele.ModeleUtilisateur;
import EncryptionDecryption.AES;
import Fichier.Fichier;
import Modele.Employe;
import Modele.Utilisateur;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author faisalhotak
 */
public class Fenetre_Parametres extends javax.swing.JFrame {

    private final ArrayList<Employe> listeEmployes;
    private final ModeleUtilisateur leModeleUtilisateur = new ModeleUtilisateur();
    private boolean ajout = false, modif = false, supp = false;
    
    public Fenetre_Parametres(ArrayList<Employe> listeEmployes){
        initComponents();
        complementGUI();
        chargerLesParametres();
        this.listeEmployes = listeEmployes;   
        
         // On remplit la comboBox Employes avec les données de l'arraylist
        chargerLesEmployes();
    }

    private void complementGUI(){
        setTitle("Générerateur de fichiers");
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator = new javax.swing.JSeparator();
        jLab_Ecran = new javax.swing.JLabel();
        jLabel_Username1 = new javax.swing.JLabel();
        jLab_UserMDP1 = new javax.swing.JLabel();
        jText_NomAdmin = new javax.swing.JTextField();
        jPasswordField_Admin = new javax.swing.JPasswordField();
        jLab_Driver = new javax.swing.JLabel();
        jLab_Serveur = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLab_UserMDP = new javax.swing.JLabel();
        jLabel_Rights = new javax.swing.JLabel();
        jText_Driver = new javax.swing.JTextField();
        jText_Serveur = new javax.swing.JTextField();
        jText_NomUtilisateur = new javax.swing.JTextField("");
        jPasswordField_User = new javax.swing.JPasswordField();
        jBtn_Valider_Parametres = new javax.swing.JButton();
        jBtn_Quitter = new javax.swing.JButton();
        jBtn_AddUser = new javax.swing.JButton();
        jBtn_DeleteUser = new javax.swing.JButton();
        jComboBox_Rights = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable(leModeleUtilisateur);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton_Visible = new javax.swing.JToggleButton();
        jBtn_EditUser = new javax.swing.JButton();
        jComboBox_Employes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jBtn_Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 10, 450));

        jLab_Ecran.setFont(new java.awt.Font("Courier", 0, 24)); // NOI18N
        jLab_Ecran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLab_Ecran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/options.png"))); // NOI18N
        jLab_Ecran.setText(" Paramètres");
        getContentPane().add(jLab_Ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 380, 50));

        jLabel_Username1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel_Username1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/utilisateur.png"))); // NOI18N
        jLabel_Username1.setText("Nom admin");
        getContentPane().add(jLabel_Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        jLab_UserMDP1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLab_UserMDP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/key.png"))); // NOI18N
        jLab_UserMDP1.setText("Mdp admin");
        getContentPane().add(jLab_UserMDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        jText_NomAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jText_NomAdmin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(jText_NomAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 190, 30));

        jPasswordField_Admin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jPasswordField_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 190, 30));

        jLab_Driver.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLab_Driver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/driver.png"))); // NOI18N
        jLab_Driver.setText("Driver SGBD");
        getContentPane().add(jLab_Driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jLab_Serveur.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLab_Serveur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/serveur.png"))); // NOI18N
        jLab_Serveur.setText("Serveur BD");
        getContentPane().add(jLab_Serveur, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jLabel_Username.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel_Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/utilisateur.png"))); // NOI18N
        jLabel_Username.setText("Nom d'utilisateur");
        getContentPane().add(jLabel_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLab_UserMDP.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLab_UserMDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/key.png"))); // NOI18N
        jLab_UserMDP.setText("Mdp utilisateur");
        getContentPane().add(jLab_UserMDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        jLabel_Rights.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel_Rights.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/star.png"))); // NOI18N
        jLabel_Rights.setText("Privilèges");
        getContentPane().add(jLabel_Rights, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 70, -1));

        jText_Driver.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jText_Driver.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(jText_Driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 270, 30));

        jText_Serveur.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jText_Serveur.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(jText_Serveur, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 270, 30));

        jText_NomUtilisateur.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jText_NomUtilisateur.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(jText_NomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 180, 30));

        jPasswordField_User.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jPasswordField_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 180, 30));

        jBtn_Valider_Parametres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtn_Valider_Parametres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/valider.png"))); // NOI18N
        jBtn_Valider_Parametres.setText("Générer");
        jBtn_Valider_Parametres.setMaximumSize(new java.awt.Dimension(84, 40));
        jBtn_Valider_Parametres.setMinimumSize(new java.awt.Dimension(84, 40));
        jBtn_Valider_Parametres.setPreferredSize(new java.awt.Dimension(84, 40));
        jBtn_Valider_Parametres.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jBtn_Valider_Parametres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Valider_ParametresActionPerformed(evt);
            }
        });
        jBtn_Valider_Parametres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_Valider_ParametresjBtn_SauvegarderKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Valider_Parametres, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 120, 40));

        jBtn_Quitter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/quitter.png"))); // NOI18N
        jBtn_Quitter.setText("Quitter");
        jBtn_Quitter.setMaximumSize(new java.awt.Dimension(80, 40));
        jBtn_Quitter.setMinimumSize(new java.awt.Dimension(80, 40));
        jBtn_Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtn_QuitterMouseReleased(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 120, 60));

        jBtn_AddUser.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jBtn_AddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_client/Ajout.png"))); // NOI18N
        jBtn_AddUser.setText(" Ajouter");
        jBtn_AddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn_AddUserMousePressed(evt);
            }
        });
        getContentPane().add(jBtn_AddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, -1));

        jBtn_DeleteUser.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jBtn_DeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_client/remove.png"))); // NOI18N
        jBtn_DeleteUser.setText(" Retirer");
        jBtn_DeleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn_DeleteUserMousePressed(evt);
            }
        });
        getContentPane().add(jBtn_DeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 110, -1));

        jComboBox_Rights.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jComboBox_Rights.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Lecture/Ecriture/Modification", "Tous les droits" }));
        getContentPane().add(jComboBox_Rights, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 180, 30));

        jTable_Users.setModel(leModeleUtilisateur);
        jScrollPane1.setViewportView(jTable_Users);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 480, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paramètres de connexion à la base de données");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 360, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion des utilisateurs");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 230, 30));

        jToggleButton_Visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_client/visible.png"))); // NOI18N
        jToggleButton_Visible.setToolTipText("Afficher les mots de passe cryptés");
        jToggleButton_Visible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton_VisibleMouseReleased(evt);
            }
        });
        getContentPane().add(jToggleButton_Visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 40));

        jBtn_EditUser.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jBtn_EditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_client/Modifier.png"))); // NOI18N
        jBtn_EditUser.setText("Modifier");
        jBtn_EditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn_EditUserMousePressed(evt);
            }
        });
        getContentPane().add(jBtn_EditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 120, -1));

        jComboBox_Employes.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        getContentPane().add(jComboBox_Employes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 555, 180, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/parametres.png"))); // NOI18N
        jLabel3.setText("Employé");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        jBtn_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_client/statut_on.png"))); // NOI18N
        jBtn_Valider.setText("Valider");
        jBtn_Valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn_ValiderMousePressed(evt);
            }
        });
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 90, 50));
        jBtn_Valider.setVisible(false);

        setSize(new java.awt.Dimension(913, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_Valider_ParametresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Valider_ParametresActionPerformed
        genererFichierParametres();  
    }//GEN-LAST:event_jBtn_Valider_ParametresActionPerformed

    private void jBtn_Valider_ParametresjBtn_SauvegarderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_Valider_ParametresjBtn_SauvegarderKeyPressed
        genererFichierParametres();
    }//GEN-LAST:event_jBtn_Valider_ParametresjBtn_SauvegarderKeyPressed

    private void jBtn_QuitterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_QuitterMouseReleased
        this.dispose();
    }//GEN-LAST:event_jBtn_QuitterMouseReleased

    private void jBtn_AddUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_AddUserMousePressed
        if (!ajout && !modif && !supp){
            if (jText_NomUtilisateur.getText().isEmpty() || 
                String.valueOf(jPasswordField_User.getPassword()).isEmpty() ||
                jComboBox_Rights.getSelectedIndex() == -1 || 
                jComboBox_Employes.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Veuillez correctement remplir le formulaire ci-dessous !", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        
            Utilisateur nouvelUtilisateur = new Utilisateur();
            nouvelUtilisateur.setNomUtilisateur(jText_NomUtilisateur.getText());
            String mdpCrypte = AES.encrypt(String.valueOf(jPasswordField_User.getPassword()));
            nouvelUtilisateur.setMdp(mdpCrypte);
            nouvelUtilisateur.setDroits(jComboBox_Rights.getSelectedIndex());
            nouvelUtilisateur.setlEmploye(listeEmployes.get(jComboBox_Employes.getSelectedIndex()));

            leModeleUtilisateur.creerMOD(nouvelUtilisateur);     
            jToggleButton_Visible.setSelected(false);
        }       
    }//GEN-LAST:event_jBtn_AddUserMousePressed

    private void jToggleButton_VisibleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton_VisibleMouseReleased
        leModeleUtilisateur.mdpVisibles(jToggleButton_Visible.isSelected());
    }//GEN-LAST:event_jToggleButton_VisibleMouseReleased

    private void jBtn_DeleteUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_DeleteUserMousePressed
        if (!ajout && !modif && !supp){
            String id;
            int index;
            boolean supres;

            index = jTable_Users.getSelectedRow();

            if (ajout){
                JOptionPane.showMessageDialog(null, "Veuillez d'abord terminer vos ajouts.", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }
            else if (modif){
                JOptionPane.showMessageDialog(null, "Veuillez d'abord terminer vos modifications.", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }
            else if (index == -1) {
                JOptionPane.showMessageDialog(null, "Aucun élément selectionné !", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }
            else {           
                supp = true;
                int choix = JOptionPane.showOptionDialog(null, "Cet enregistrement sera supprimé, en êtes-vous sûr ?", "Suppression d'un enregistrement", 
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, new String[] {"Oui", "Non"}, null);
                if (choix == 0){
                    id = String.valueOf(leModeleUtilisateur.getValueAt(index, 0));
                    supres = leModeleUtilisateur.supprimerMOD(index, id);
                    jTable_Users.clearSelection();

                    if (supres){    
                        JOptionPane.showMessageDialog(null, "Enregistrement " + id + " supprimé !", "Suppression", JOptionPane.INFORMATION_MESSAGE);                                                  
                    }               
                }
                supp = false;
            }//fin suppression
        }       
    }//GEN-LAST:event_jBtn_DeleteUserMousePressed

    private void jBtn_EditUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_EditUserMousePressed
        if (!ajout && !modif && !supp){
            int indexSelected = jTable_Users.getSelectedRow();
            if (indexSelected == -1) {
                JOptionPane.showMessageDialog(null, "Aucun élément selectionné !", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {
                modif = true;
                Utilisateur util = leModeleUtilisateur.getLesDonnees().get(indexSelected);
                jText_NomUtilisateur.setText(util.getNomUtilisateur());
                String mdp = util.getMdp();
                if (!jToggleButton_Visible.isSelected()) mdp = AES.decrypt(mdp);
                jPasswordField_User.setText(mdp);
                jComboBox_Rights.setSelectedIndex(util.getDroits());
                jComboBox_Employes.setSelectedIndex(listeEmployes.indexOf(util.getlEmploye()));
                jBtn_AddUser.setEnabled(false);
                jBtn_DeleteUser.setEnabled(false);
                jBtn_EditUser.setEnabled(false);
                jBtn_Valider.setVisible(true);
                jTable_Users.setEnabled(false);
                jToggleButton_Visible.setVisible(false);
            }
        }        
    }//GEN-LAST:event_jBtn_EditUserMousePressed

    private void jBtn_ValiderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ValiderMousePressed
        int selectedIndex = jTable_Users.getSelectedRow();
        if (selectedIndex !=1){
            if (jText_NomUtilisateur.getText().isEmpty() || 
                String.valueOf(jPasswordField_User.getPassword()).isEmpty() ||
                jComboBox_Rights.getSelectedIndex() == -1 || 
                jComboBox_Employes.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Veuillez correctement remplir le formulaire ci-dessous !", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        
            Utilisateur lUtilisateur = leModeleUtilisateur.getLesDonnees().get(selectedIndex);
            lUtilisateur.setNomUtilisateur(jText_NomUtilisateur.getText());
            String mdp = String.valueOf(jPasswordField_User.getPassword());
            if (!jToggleButton_Visible.isSelected()) mdp = AES.encrypt(mdp);
            lUtilisateur.setMdp(mdp);
            lUtilisateur.setDroits(jComboBox_Rights.getSelectedIndex());
            lUtilisateur.setlEmploye(listeEmployes.get(jComboBox_Employes.getSelectedIndex()));
              
            boolean modifier = leModeleUtilisateur.modifierMOD(selectedIndex, selectedIndex, lUtilisateur);
            
            if(modifier){
                jBtn_AddUser.setEnabled(true);
                jBtn_DeleteUser.setEnabled(true);
                jBtn_EditUser.setEnabled(true);
                jTable_Users.setEnabled(true);
                jBtn_Valider.setVisible(false);
                modif = false;
                jToggleButton_Visible.setVisible(true);
                reinitFormulaire();
            }            
        }        
    }//GEN-LAST:event_jBtn_ValiderMousePressed
   
    private void genererFichierParametres(){
        String encryptedString;
        String path = "files/parametres.enc";
        String nom = jText_NomAdmin.getText();
        String mdp = String.valueOf(jPasswordField_Admin.getPassword());
        String driver = jText_Driver.getText();
        String serveur = jText_Serveur.getText();       
        
        encryptedString = AES.encrypt(nom + "\n" + mdp + "\n" + driver + "\n" + serveur);
        Fichier.ecrire(encryptedString, path);
        JOptionPane.showMessageDialog(null, "Fichier de paramètres généré avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void chargerLesParametres(){
        String donneesLues, decryptedString;      
        String path = "files/parametres.enc";
        donneesLues = Fichier.lire(path);
                             
        if (donneesLues != null){       
            String[] split;

            decryptedString = AES.decrypt(donneesLues);
            split = decryptedString.split("\n");
            
            jText_NomAdmin.setText(split[0]);
            jPasswordField_Admin.setText(split[1]);
            jText_Driver.setText(split[2]);
            jText_Serveur.setText(split[3]);           
        }  
    }
    
    private void chargerLesEmployes(){
        String nom, prenom;
        
        for (Employe lEmploye : listeEmployes) {
            nom = lEmploye.getNom() == null ? "" : lEmploye.getNom();
            prenom = lEmploye.getPrenom() == null ? "" : lEmploye.getPrenom();
            jComboBox_Employes.addItem(nom + " " + prenom);
        }
        
        jComboBox_Employes.setSelectedIndex(0);
    }

    private void reinitFormulaire(){
        this.jText_NomUtilisateur.setText("");
        this.jPasswordField_User.setText(""); 
        this.jComboBox_Employes.setSelectedIndex(0);
        this.jComboBox_Rights.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Fenetre_Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Fenetre_Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Fenetre_Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Fenetre_Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Fenetre_Parametres().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_AddUser;
    private javax.swing.JButton jBtn_DeleteUser;
    private javax.swing.JButton jBtn_EditUser;
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JButton jBtn_Valider_Parametres;
    private javax.swing.JComboBox<String> jComboBox_Employes;
    private javax.swing.JComboBox<String> jComboBox_Rights;
    private javax.swing.JLabel jLab_Driver;
    private javax.swing.JLabel jLab_Ecran;
    private javax.swing.JLabel jLab_Serveur;
    private javax.swing.JLabel jLab_UserMDP;
    private javax.swing.JLabel jLab_UserMDP1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Rights;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JLabel jLabel_Username1;
    private javax.swing.JPasswordField jPasswordField_Admin;
    private javax.swing.JPasswordField jPasswordField_User;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jText_Driver;
    private javax.swing.JTextField jText_NomAdmin;
    private javax.swing.JTextField jText_NomUtilisateur;
    private javax.swing.JTextField jText_Serveur;
    private javax.swing.JToggleButton jToggleButton_Visible;
    // End of variables declaration//GEN-END:variables
}
