package Vue;

import  java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Controle.ControleConnexionSingleton;
import java.awt.Color;

public class Fenetre_Connexion extends javax.swing.JFrame {

    int xx = 0;
    int yy = 0;
    
    public Fenetre_Connexion() {
        initComponents();
        complementGUI();       
    }
    
    private void complementGUI() {
        setTitle("Connexion au Supermarché");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Gauche = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Droit = new javax.swing.JPanel();
        jLab_Nom = new javax.swing.JLabel();
        jText_Nom = new javax.swing.JTextField("admin");
        jLab_MDP = new javax.swing.JLabel();
        jPasF_Password = new javax.swing.JPasswordField("admin");
        jBtn_Valider = new javax.swing.JButton();
        jBtn_Quitter = new javax.swing.JButton();
        jLabel_Fermer = new javax.swing.JLabel();
        jLabel_Reduire = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion au programme");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Gauche.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_Gauche.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_new.png"))); // NOI18N
        jPanel_Gauche.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 550, 360));

        jPanel1.add(jPanel_Gauche, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 360));

        jPanel_Droit.setBackground(new java.awt.Color(107, 140, 94));
        jPanel_Droit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_Nom.setForeground(new java.awt.Color(255, 255, 255));
        jLab_Nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/utilisateur.png"))); // NOI18N
        jLab_Nom.setText(" Nom");
        jPanel_Droit.add(jLab_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, 30));

        jText_Nom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel_Droit.add(jText_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 190, 30));

        jLab_MDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLab_MDP.setForeground(new java.awt.Color(255, 255, 255));
        jLab_MDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/key.png"))); // NOI18N
        jLab_MDP.setText(" Mot de passe");
        jPanel_Droit.add(jLab_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 130, 30));

        jPasF_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_Droit.add(jPasF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 190, 30));

        jBtn_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/valider.png"))); // NOI18N
        jBtn_Valider.setText("Connexion");
        jBtn_Valider.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });
        jBtn_Valider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_ValiderKeyPressed(evt);
            }
        });
        jPanel_Droit.add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 110, 50));

        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connection/quitter.png"))); // NOI18N
        jBtn_Quitter.setText("Quitter");
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        jBtn_Quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_QuitterKeyPressed(evt);
            }
        });
        jPanel_Droit.add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 110, 50));

        jLabel_Fermer.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel_Fermer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Fermer.setText("X");
        jLabel_Fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_FermerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_FermerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_FermerMouseExited(evt);
            }
        });
        jPanel_Droit.add(jLabel_Fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 2, 30, 40));

        jLabel_Reduire.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel_Reduire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Reduire.setText("-");
        jLabel_Reduire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ReduireMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ReduireMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ReduireMouseExited(evt);
            }
        });
        jPanel_Droit.add(jLabel_Reduire, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 2, 30, 40));

        jPanel1.add(jPanel_Droit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 350));

        setSize(new java.awt.Dimension(820, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        ControleConnexionSingleton.fermetureConnect();
        System.exit(0);
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    private void jBtn_QuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_QuitterKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ControleConnexionSingleton.fermetureConnect();
            System.exit(0);
        }
    }//GEN-LAST:event_jBtn_QuitterKeyPressed

    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
        Fenetre_Gestion     Fenetre;
        
        if(controleConnexion_Appel()){
            Fenetre = new Fenetre_Gestion();
            
            Fenetre.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    private void jBtn_ValiderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_ValiderKeyPressed
        Fenetre_Gestion     Fenetre;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(controleConnexion_Appel()){
                Fenetre = new Fenetre_Gestion();               
                
                Fenetre.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_jBtn_ValiderKeyPressed

    private void jLabel_FermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FermerMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_FermerMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel_FermerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FermerMouseEntered
        this.jLabel_Fermer.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_FermerMouseEntered

    private void jLabel_FermerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FermerMouseExited
        this.jLabel_Fermer.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_FermerMouseExited

    private void jLabel_ReduireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ReduireMouseClicked
        this.setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel_ReduireMouseClicked

    private void jLabel_ReduireMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ReduireMouseEntered
        this.jLabel_Reduire.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_ReduireMouseEntered

    private void jLabel_ReduireMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ReduireMouseExited
        this.jLabel_Reduire.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_ReduireMouseExited
    
    private boolean controleConnexion_Appel() {
        
        // contrôle de la saisie
        String leNom = jText_Nom.getText();
        boolean bControle = false;
        String leMotDePasse = String.valueOf(jPasF_Password.getPassword());        
        
        if(ControleConnexionSingleton.controle(leNom, leMotDePasse))
        {
            if (ControleConnexionSingleton.isEtatConnexion()) {
                bControle = true;
            } else {
                JOptionPane.showMessageDialog(null,
                        "Impossible de se connecter"
                        + " à la base de données.\n\n"
                        + "Vos nom et mot de passe sont corrects.\n"
                        + "Mais les paramètres pour le pilote"
                        + " et la base de données "
                        + "doivent être vérifiés.\n\n"
                        + "Contacter le responsable informatique.",
                        "ALERTE", JOptionPane.ERROR_MESSAGE);
            }
        }
        else JOptionPane.showMessageDialog(null,
                        "Vérifier votre saisie.",
                        "ERREUR", JOptionPane.ERROR_MESSAGE);
        return bControle;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ControleConnexionSingleton.getInstance();
                
                if(ControleConnexionSingleton.isEtatConnexion()) {
                    
                    new Fenetre_Connexion().setVisible(true);
                    
                }
                else JOptionPane.showMessageDialog(null,
                        "Impossible de se connecter"
                        + " à la base de données.\n\n"
                        + "Les paramètres pour le pilote"
                        + " et de la base de données "
                        + "doivent être vérifiés.\n\n"
                        + "Contacter le responsable informatique.",
                        "ALERTE", JOptionPane.ERROR_MESSAGE);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JLabel jLab_MDP;
    private javax.swing.JLabel jLab_Nom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Fermer;
    private javax.swing.JLabel jLabel_Reduire;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Droit;
    private javax.swing.JPanel jPanel_Gauche;
    private javax.swing.JPasswordField jPasF_Password;
    private javax.swing.JTextField jText_Nom;
    // End of variables declaration//GEN-END:variables
}
